#!/bin/bash

REGISTRY_URL="https://ghcr.io"
USERNAME="workinright"
PASSWORD="$(cat "$HOME/github_credentials" | rev | cut -d' ' -f1 | rev)"

# Get the token for authentication
TOKEN="$(curl -L -s \
    -u "${USERNAME}:${PASSWORD}" \
    "$REGISTRY_URL/token?scope=repository:${USERNAME}/openpilot-base:push" | jq -r .token)"
echo TOKEN $TOKEN

OCI_IMAGE_DIR="."

#for LAYER in "$OCI_IMAGE_DIR/blobs/sha256"/*
#do
    #echo $LAYER
    #LAYER_DIGEST="$(sha256sum $LAYER | awk '{print $1}')"

    # Create a blob upload session for the layer
    

    # TODO manifest - one for platform, on both upload and download
    manifest_sha256="$(jq -r '.manifests[0].digest' index.json | cut -d':' -f2)"
    layers="$(jq -r '.layers[]' "blobs/sha256/$manifest_sha256" | tr -d '\n' | sed 's/}/} \n/g')"

    config_mediaType="$(jq -r '.config.mediaType' "blobs/sha256/$manifest_sha256")"
    config_digest="$(jq -r '.config.digest' "blobs/sha256/$manifest_sha256" | cut -d':' -f2)"

    i=0
    while read layer
    do
        sha256="$(echo -n "$layer" | jq -r '.digest' | cut -d':' -f2)"
        mediaType="$(echo -n "$layer" | jq -r '.mediaType')"

        #echo curl -s -D - -X POST \
        #-H "Authorization: Bearer $TOKEN" \
        #-H "Content-Type: $mediaType" \
        #-H "Content-Length: $(stat --format=%s blobs/sha256/$sha256)" \
        #--data-binary @blobs/sha256/$sha256 "$REGISTRY_URL/v2/${USERNAME}/openpilot-base/blobs/uploads/"
        
        location="$(curl -s -D /proc/self/fd/1 -X POST \
        -H "Authorization: Bearer $TOKEN" \
        -H "Content-Type: application/octet-stream" \
        -H "Content-Length: $(stat --format=%s blobs/sha256/$sha256)" \
         "$REGISTRY_URL/v2/${USERNAME}/openpilot-base/blobs/uploads/" | tr -d '\r' | grep location | cut -d':' -f2 | cut -d' ' -f2)"

        echo LOCATION $location

        echo abcd $location ${REGISTRY_URL} ?digest=sha256%3A ${sha256}

        curl -X PUT \
          -H "Authorization: Bearer $TOKEN" \
          -H "Content-Type: application/octet-stream" \
          -H "Content-Length: $(stat --format=%s blobs/sha256/$sha256)" \
          --data-binary @blobs/sha256/$sha256 "$REGISTRY_URL$location?digest=sha256:$sha256"


        echo "${REGISTRY_URL}${location}?digest=sha256%3A$sha256"

        ((++i))
    done <<< "$layers"


    echo "Uploaded layer: $LAYER"
#done

location="$(curl -s -D /proc/self/fd/1 -X POST \
    -H "Authorization: Bearer $TOKEN" \
    -H "Content-Type: application/octet-stream" \
    -H "Content-Length: $(stat --format=%s blobs/sha256/$config_digest)" \
        "$REGISTRY_URL/v2/${USERNAME}/openpilot-base/blobs/uploads/" | tr -d '\r' | grep location | cut -d':' -f2 | cut -d' ' -f2)"

    echo LOCATION $location

    echo abcd $location ${REGISTRY_URL} ?digest=sha256%3A ${sha256}

    curl -X PUT \
        -H "Authorization: Bearer $TOKEN" \
        -H "Content-Type: application/octet-stream" \
        -H "Content-Length: $(stat --format=%s blobs/sha256/$config_digest)" \
        --data-binary @blobs/sha256/$config_digest "$REGISTRY_URL$location?digest=sha256:$config_digest"

IMAGE_NAME="workinright/openpilot-base"
IMAGE_TAG="latest"

echo "$MANIFEST"

curl -X PUT \
    -H "Authorization: Bearer $TOKEN" \
    -H "Content-Type: application/vnd.docker.distribution.manifest.v2+json" \
    --data-binary @blobs/sha256/$manifest_sha256 \
    "$REGISTRY_URL/v2/${IMAGE_NAME}/manifests/${IMAGE_TAG}"

echo "Pushed manifest for image ${IMAGE_NAME}:${IMAGE_TAG}"
