name: 'openpilot env setup'

inputs:
  is_retried:
    description: 'A mock param that asserts that we use the setup-with-retry instead of this action directly'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    # assert that this action is retried using the setup-with-retry
    - shell: bash
      if: ${{ inputs.is_retried == 'false' }}
      run: |
        echo "You should not run this action directly. Use setup-with-retry instead"
        exit 1

    - shell: bash
      name: No retries!
      run: |
        if [ "${{ github.run_attempt }}" -gt 1 ]; then
          echo -e "\033[0;31m##################################################"
          echo -e "\033[0;31m    Retries not allowed! Fix the flaky test!      "
          echo -e "\033[0;31m##################################################\033[0m"
          exit 1
        fi

    # do this after checkout to ensure our custom LFS config is used to pull from GitLab
    - shell: bash
      run: git lfs pull

    # build cache
    - id: date
      shell: bash
      run: echo "CACHE_COMMIT_DATE=$(git log -1 --pretty='format:%cd' --date=format:'%Y-%m-%d-%H:%M')" >> $GITHUB_ENV ; echo "LAST_COMMIT_HASH=$(git log -1 --pretty='format:%H')" >> $GITHUB_ENV
    - shell: bash
      run: echo "$CACHE_COMMIT_DATE" ; echo "$LAST_COMMIT_HASH"
    - id: scons-cache
      uses: ./.github/workflows/auto-cache
      with:
        path: .ci_cache/scons_cache
        key: scons-${{ runner.arch }}-${{ env.CACHE_COMMIT_DATE }}-${{ github.sha }}
        restore-keys: |
          scons-${{ runner.arch }}-${{ env.CACHE_COMMIT_DATE }}
          scons-${{ runner.arch }}
    - id: rootfs-cache
      uses: ./.github/workflows/auto-cache
      with:
        path: /tmp/rootfs_cache/rootfs_cache.tar.zstd
        key: rootfs-${{ runner.arch }}-${{ env.CACHE_COMMIT_DATE }}-${{ env.LAST_COMMIT_HASH }}
        restore-keys: |
          rootfs-${{ runner.arch }}-${{ env.CACHE_COMMIT_DATE }}
          rootfs-${{ runner.arch }}
    # build our docker image
    - shell: bash
      run: eval ${{ env.BUILD }}
    - name: Save rootfs cache
      uses: actions/cache/save@v4
      #if: github.ref == 'refs/heads/master'
      with:
        path: /tmp/rootfs_cache/rootfs_cache.tar.zstd
        key: rootfs-${{ runner.arch }}-${{ env.CACHE_COMMIT_DATE }}-${{ env.LAST_COMMIT_HASH }}
