name: 'compile openpilot'

runs:
  using: "composite"
  steps:
    - shell: bash
      name: Build openpilot with all flags
      run: |
        ${{ env.RUN }} "export UV_BIN="/home/batman/.local/bin" ; export PATH="$UV_BIN:$PATH" ; source /home/batman/.venv/bin/activate ; pwd ; sudo chown -R batman:batman /home/runner; scons -j$(nproc) ; sudo chown -R runner:runner /home/runner"
        ${{ env.RUN }} "export UV_BIN="/home/batman/.local/bin" ; export PATH="$UV_BIN:$PATH" ; source /home/batman/.venv/bin/activate ; pwd ; sudo chown -R batman:batman /home/runner; release/check-dirty.sh ; sudo chown -R runner:runner /home/runner"
    - shell: bash
      name: Cleanup scons cache and rebuild
      run: |
          ${{ env.RUN }} "export UV_BIN="/home/batman/.local/bin" ; export PATH="$UV_BIN:$PATH" ; source /home/batman/.venv/bin/activate ; pwd ; sudo chown -R batman:batman /home/runner; rm -rf /tmp/scons_cache/* && \
                          scons -j$(nproc) --cache-populate ; sudo chown -R runner:runner /home/runner"
    - name: Save scons cache
      uses: actions/cache/save@v4
      if: github.ref == 'refs/heads/master'
      with:
        path: .ci_cache/scons_cache
        key: scons-${{ runner.arch }}-${{ env.CACHE_COMMIT_DATE }}-${{ github.sha }}
