name: 'compile openpilot'

runs:
  using: "composite"
  steps:
    - shell: bash
      name: Build openpilot with all flags
      run: |
        sudo -u batman bash -c "mount ; echo $PATH ; export UV_BIN="/home/batman/.local/bin" ; export PATH="$UV_BIN:$PATH" ; source /home/batman/.venv/bin/activate ; pwd ; sudo chown -R batman:batman /home/runner/work ; scons -j$(nproc) ; release/check-dirty.sh ; sudo chown -R runner:runner /home/runner"
